name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - run: pnpm install
      - run: pnpm build

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/@nju-helper/script.user.js
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
